CREATE TABLE IF NOT EXISTS shop_registrations (
    id BIGINT NOT NULL AUTO_INCREMENT,
    registration_id VARCHAR(64) NOT NULL,
    shop_unique_id VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    current_step INT NULL,
    owner_full_name VARCHAR(120) NULL,
    email VARCHAR(160) NULL,
    phone_number VARCHAR(20) NULL,
    password_hash VARCHAR(255) NULL,
    email_otp VARCHAR(12) NULL,
    email_otp_verified BIT NULL,
    phone_otp VARCHAR(12) NULL,
    phone_otp_verified BIT NULL,
    profile_photo VARCHAR(255) NULL,
    shop_name VARCHAR(180) NULL,
    shop_category VARCHAR(100) NULL,
    shop_description LONGTEXT NULL,
    address_line_1 VARCHAR(200) NULL,
    address_line_2 VARCHAR(200) NULL,
    city VARCHAR(120) NULL,
    state VARCHAR(120) NULL,
    pincode VARCHAR(12) NULL,
    country VARCHAR(120) NULL,
    landmark VARCHAR(200) NULL,
    latitude DOUBLE NULL,
    longitude DOUBLE NULL,
    shop_phone_number VARCHAR(20) NULL,
    shop_email VARCHAR(160) NULL,
    whatsapp_number VARCHAR(20) NULL,
    owner_aadhar_number VARCHAR(20) NULL,
    owner_pan_number VARCHAR(20) NULL,
    owner_aadhar_photo VARCHAR(255) NULL,
    owner_pan_photo VARCHAR(255) NULL,
    owner_selfie_with_id VARCHAR(255) NULL,
    gst_number VARCHAR(30) NULL,
    gst_certificate_upload VARCHAR(255) NULL,
    business_registration_number VARCHAR(100) NULL,
    account_holder_name VARCHAR(120) NULL,
    bank_name VARCHAR(120) NULL,
    account_number VARCHAR(40) NULL,
    ifsc_code VARCHAR(20) NULL,
    upi_id VARCHAR(120) NULL,
    cancelled_cheque_photo VARCHAR(255) NULL,
    accept_terms_and_conditions BIT NULL,
    accept_privacy_policy BIT NULL,
    accept_commission_policy BIT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    submitted_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_shop_registrations_registration_id (registration_id),
    UNIQUE KEY uk_shop_registrations_shop_unique_id (shop_unique_id)
);