export const AUTH_FLOW_TEXT = {
	signUp: {
		nameLabel: 'Name',
		namePlaceholder: 'Eg: SHIVA',
		nameRequiredError: 'Name is required.',
		namePatternError: 'Name cannot be empty.',
		contactLabel: 'Email',
		contactPlaceholder: 'Eg: Shiva@gmail.com',
		contactRequiredError: 'Email is required.',
		contactInvalidError: 'Enter a valid email address.',
		continueButton: 'Continue',
		submittingButton: 'Sending OTP...',
		requestFailedMessage: 'Unable to send OTP right now. Please try again.',
		altPrompt: 'Already have an account?',
		altLinkText: 'Just Sign In.',
	},
	signIn: {
		emailLabel: 'Email',
		emailPlaceholder: 'Eg: Shiva@gmail.com',
		emailRequiredError: 'Email is required.',
		emailInvalidError: 'Enter a valid email address.',
		contactLabel: 'Email',
		contactPlaceholder: 'Eg: Shiva@gmail.com',
		contactRequiredError: 'Email is required.',
		contactInvalidError: 'Enter a valid email address.',
		passwordLabel: 'Password',
		passwordPlaceholder: 'Enter your password',
		passwordRequiredError: 'Password is required.',
		passwordPatternError: 'Password cannot be empty.',
		signInButton: 'Sign In',
		signingInButton: 'Signing in...',
		requestFailedMessage: 'Unable to sign in right now. Please try again.',
		forgotPasswordLinkText: 'Forgot Password?',
		forgotPasswordPromptMessage: 'Enter your valid email first to reset password.',
		forgotPasswordFailedMessage: 'Unable to send reset OTP right now. Please try again.',
		continueButton: 'Sign In',
		altPrompt: 'Need a new account?',
		altLinkText: 'Go to Sign Up.',
	},
	setPassword: {
		emailLabel: 'Email',
		emailPlaceholder: 'Eg: Shiva@gmail.com',
		emailRequiredError: 'Email is required.',
		emailInvalidError: 'Enter a valid email address.',
		passwordLabel: 'Password',
		passwordPlaceholder: 'Enter password',
		passwordRequiredError: 'Password is required.',
		passwordWeakError: 'Password must be at least 8 characters and include letters and numbers.',
		confirmPasswordLabel: 'Re-enter Password',
		confirmPasswordPlaceholder: 'Re-enter password',
		confirmPasswordRequiredError: 'Please re-enter your password.',
		confirmPasswordWeakError: 'Password must be at least 8 characters and include letters and numbers.',
		mismatchError: 'Password and re-entered password do not match.',
		submitButton: 'Set Password',
		submittingButton: 'Setting password...',
		requestFailedMessage: 'Unable to set password right now. Please try again.',
		backLinkText: 'Go back to Sign In.',
	},
	otp: {
		eyebrow: 'Verify OTP',
		title: 'Enter the 6-digit code',
		introPrefix: 'We sent a verification code to your',
		introSuffix: '.',
		namePrefix: 'for',
		otpInvalidError: 'Please enter all 6 digits of the OTP.',
		verifyButton: 'Verify OTP',
		verifyingButton: 'Verifying OTP...',
		resendPrefix: 'Resend OTP in',
		resendButton: 'Resend OTP',
		resendingButton: 'Resending...',
		wrongContactPrompt: 'Entered the wrong',
		wrongContactLink: 'Go back to Sign Up.',
		resendSuccessPrefix: 'A new OTP has been sent to',
		resendFailedMessage: 'Unable to resend OTP right now. Please try again.',
		verifyFailedMessage: 'Unable to verify OTP right now. Please try again.',
		verifySuccessMessage: 'OTP verified successfully.',
	},
};

