export const INDIAN_BANKS = [
  'State Bank of India',
  'HDFC Bank',
  'ICICI Bank',
  'Axis Bank',
  'Kotak Mahindra Bank',
  'Bank of Baroda',
  'Punjab National Bank',
  'Canara Bank',
  'Union Bank of India',
  'Bank of India',
  'Indian Bank',
  'Central Bank of India',
  'Indian Overseas Bank',
  'UCO Bank',
  'Bank of Maharashtra',
  'Punjab and Sind Bank',
  'Yes Bank',
  'IndusInd Bank',
  'IDFC FIRST Bank',
  'Federal Bank',
  'RBL Bank',
  'South Indian Bank',
  'City Union Bank',
  'Karur Vysya Bank',
  'Bandhan Bank',
  'DCB Bank',
  'AU Small Finance Bank',
  'Equitas Small Finance Bank',
  'Ujjivan Small Finance Bank',
  'Jana Small Finance Bank',
  'Airtel Payments Bank',
  'India Post Payments Bank',
  'Fino Payments Bank',
  'Jio Payments Bank',
] as const;
